import type {ProjectFlow} from './flow-schema.js';

const html = (s: string) => s.replace(/[&<>"']/g, c => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[c]!));
const label = (s: string) => html(s).replace(/\r?\n/g, '<br/>');
export function flowToMermaid(flow: ProjectFlow, scenarioId?: string) {
  const ids = new Map(flow.nodes.map((n, i) => [n.id, `n${i}`]));
  const lines = ['flowchart LR'];
  function node(id: string, indent: string) {
    const n = flow.nodes.find(n => n.id === id)!;
    const children = flow.nodes.filter(c => c.parent === id);
    const details = [n.label, ...(['props', 'state', 'events', 'lifecycle'] as const).flatMap(k => n[k].length ? [`${k}: ${n[k].join(', ')}`] : [])].map(label).join('<br/>');
    if (children.length) {
      lines.push(`${indent}subgraph ${ids.get(id)}["${label(n.label)}"]`);
      if ([n.props,n.state,n.events,n.lifecycle].some(values => values.length)) lines.push(`${indent}  ${ids.get(id)}info["${details}"]`);
      for (const child of children) node(child.id, `${indent}  `);
      lines.push(`${indent}end`);
    } else lines.push(`${indent}${ids.get(id)}["${label(n.kind)} · ${details}"]`);
  }
  for (const n of flow.nodes.filter(n => !n.parent)) node(n.id, '  ');
  const scenario = flow.scenarios.find(s => s.id === scenarioId);
  for (const [i, edge] of flow.edges.filter(e => !scenario || scenario.steps.some(s => s.edge === e.id)).entries()) {
    const steps = scenario?.steps.flatMap((s, j) => s.edge === edge.id ? [j + 1] : []) ?? [];
    lines.push(`  ${ids.get(edge.from)} -->|"${label(`${steps.length ? `${steps.join('/')} · ` : ''}${edge.label}${edge.condition ? ` [${edge.condition}]` : ''}`)}"| ${ids.get(edge.to)}`);
    if (steps.length) lines.push(`  linkStyle ${i} stroke:#0369a1,stroke-width:3px`);
  }
  return lines.join('\n') + '\n';
}

/** Offline, deterministic view. Labels are escaped and embedded data cannot close a script. */
export function flowToHtml(flow: ProjectFlow, freshness: string, options: {
  language?: 'ko' | 'en'; projectPath?: string; flowHash?: string; generatedAt?: string; reasons?: string[]; scenarioId?: string | undefined;
} = {}) {
  if (options.scenarioId && !flow.scenarios.some(s => s.id === options.scenarioId)) throw new Error('Unknown flow scenario');
  const language = options.language ?? 'ko';
  const t = (ko: string, en: string) => language === 'en' ? en : ko;
  const citation = (id: string) => {
    const c = flow.evidence[id];
    return c ? `<p><b>${html(c.path)}${c.line ? `:${c.line}` : ''}</b><br><code>${html(c.quote)}</code></p>` : '';
  };
  const statusLabel = freshness === 'current' ? t('생성 시점에 분석 대상 파일 일치', 'Analyzed files matched at export') : freshness;

  const data = JSON.stringify(flow).replace(/</g, '\\u003c').replace(/>/g, '\\u003e').replace(/&/g, '\\u0026');
  function card(id: string): string {
    const n = flow.nodes.find(n => n.id === id)!;
    const children = flow.nodes.filter(c => c.parent === id);
    return `<section class="node ${children.length ? 'group' : ''}" data-node="${html(id)}"><header><small>${html(n.kind)}</small><h2>${html(n.label)}</h2></header>${(['props','state','events','lifecycle'] as const).filter(k => n[k].length).map(k => `<p><b>${k}</b> ${n[k].map(html).join(' · ')}</p>`).join('')}${children.length ? `<div class="children">${children.map(c => card(c.id)).join('')}</div>` : ''}<details><summary>${t('근거', 'Evidence')}</summary>${n.evidence.map(citation).join('') || `<p>${t('제안된 구조', 'Proposed structure')}</p>`}</details></section>`;
  }
  return `<!doctype html><html lang="${language}"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${html(flow.title)}</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f2f5f7;color:#182934;font:15px/1.5 system-ui,sans-serif}main{max-width:1580px;margin:auto;padding:28px}h1{font-size:28px;margin:0 0 8px}h2{font-size:17px;margin:2px 0 10px}small{color:#536675;text-transform:uppercase;letter-spacing:.07em}p{margin:5px 0}button,select{font:inherit;padding:9px;border:1px solid #879ba8;border-radius:7px;background:white;color:#182934}button{cursor:pointer}button:focus-visible,select:focus-visible{outline:3px solid #0987c5}.bar{display:flex;gap:14px;align-items:center;margin:20px 0;flex-wrap:wrap}.badge{padding:4px 10px;border-radius:20px;background:#e5eaf0}.layout{display:grid;grid-template-columns:minmax(0,1fr) 290px;gap:24px}.map{position:relative;display:grid;grid-template-columns:minmax(0,2fr) minmax(220px,1fr);gap:58px;align-content:start}.node{position:relative;z-index:1;border:1px solid #b6c5cf;border-radius:12px;padding:15px;background:white;transition:opacity .15s,border-color .15s}.node.group{background:#eaf0f5}.children{display:grid;gap:24px;margin:18px 10px 4px}.node p{font-size:13px;overflow-wrap:anywhere}.node b{color:#486174;font-size:11px;display:inline-block;min-width:54px}.node.affected{border:2px solid #31a4c4}.node.active{border-color:#c65c0b;box-shadow:0 0 0 3px #f4c896}.node.dim{opacity:.55}.external{display:grid;gap:26px;align-content:start}.pages{display:grid;gap:26px}svg{position:absolute;inset:0;z-index:2;pointer-events:none;overflow:visible}aside{border:1px solid #cad5dd;border-radius:12px;background:white;padding:16px;align-self:start}ol{padding-left:20px}li{margin:8px 0}li button{width:100%;text-align:left;font-size:13px}li button.selected{background:#fff0dc;border-color:#c65c0b}.muted{color:#536675}code{overflow-wrap:anywhere}.limit p{overflow-wrap:anywhere}aside{min-width:0}details{font-size:12px;margin-top:12px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#eaf0f5;padding:15px}summary{cursor:pointer}.legend{margin-top:16px;font-size:13px}.limit{margin-top:20px;max-width:1000px}@media(max-width:900px){.layout{grid-template-columns:1fr}.map{grid-template-columns:1fr;gap:30px}main{padding:15px}aside{order:-1}}@media(prefers-reduced-motion:reduce){*{transition:none!important}}
</style><main><small>FS · ${t('페이지 구성과 이벤트 영향', 'Page structure and event effects')}</small><h1>${html(flow.title)}</h1><p>${html(flow.summary)}</p><div class="bar"><span class="badge">${flow.basis === 'observed' ? t('코드에서 해석한 흐름', 'Interpreted from code') : t('설계 예시 · 구현 사실 아님', 'Proposed design · not implementation evidence')}</span><span class="badge">${html(statusLabel)}</span><label>${t('이벤트', 'Event')} <select id="scenario">${flow.scenarios.map(s => `<option value="${html(s.id)}"${s.id === options.scenarioId ? ' selected' : ''}>${html(s.title)}</option>`).join('')}</select></label><button id="previous">${t('이전 단계', 'Previous step')}</button><button id="next">${t('다음 단계', 'Next step')}</button></div>
<div class="layout"><div class="map" id="map"><div class="pages">${flow.nodes.filter(n => !n.parent && n.kind === 'page').map(n => card(n.id)).join('')}</div><div class="external">${flow.nodes.filter(n => !n.parent && n.kind !== 'page').map(n => card(n.id)).join('')}</div><svg id="edges" aria-hidden="true"></svg></div><aside><h2 id="event"></h2><p id="outcome" class="muted"></p><ol id="steps"></ol><p id="effect" role="status" aria-live="polite"></p><details id="edge-evidence" open><summary>${t('선택한 관계의 코드 근거', 'Code evidence for selected relation')}</summary><div id="edge-citations"></div></details><div class="legend">${t('청록: 이 이벤트의 영향 범위', 'Teal: affected by this event')}<br>${t('주황: 선택한 단계의 출발·도착 블록', 'Orange: source and destination of selected step')}<br>${t('화살표: 선택한 호출/읽기/쓰기 관계', 'Arrow: selected call/read/write relation')}<br>${t('순서는 기록한 시나리오의 순서입니다.', 'Order follows the recorded scenario.')}</div></aside></div>
<div class="limit"><b>${t('분석 출처', 'Analysis provenance')}</b><p>${html(options.projectPath ?? t('출처 경로 미지정', 'Project path not provided'))}</p><p>${t('생성:', 'Generated:')} ${html(options.generatedAt ?? t('미기록', 'Not recorded'))} · ${t('분석 버전:', 'Analysis version:')} <code>${html(options.flowHash ?? t('미기록', 'Not recorded'))}</code></p><p>${t('오프라인 파일은 생성 당시의 상태입니다. 이후 코드 변경 여부는 다시 생성할 때 확인합니다.', 'This offline file captures export-time state. Rerender to check later code changes.')}</p>${flow.scope.snapshot ? `<p>${t('Git 기준:', 'Git basis:')} ${html(flow.scope.snapshot.baseRef)} · ${html(flow.scope.snapshot.expectedCommit)}</p>` : `<p>${t('기준: 분석 당시의 작업 폴더 코드', 'Basis: working-tree code at analysis time')}</p>`}<ul>${(options.reasons ?? []).map(r => `<li>${html(r)}</li>`).join('')}</ul><details><summary>${t('분석한 파일과 새 파일 탐색 범위', 'Analyzed files and discovery scope')}</summary><ul>${flow.scope.files.map(p => `<li>${html(p)}</li>`).join('')}</ul><p>${t('새 파일 탐색:', 'Discovery:')} ${flow.scope.discoveryRoots.map(html).join(', ')}</p></details><details><summary>${t('기록된 동작과 규칙', 'Recorded behavior and rules')}</summary>${flow.invariants.map(i => `<p><b>${html(i.authority)}</b> ${html(i.statement)}</p>${i.evidence.map(citation).join('')}`).join('') || `<p>${t('별도 기록 없음', 'No additional records')}</p>`}</details><b>${t('분석 범위와 미확인', 'Scope and unknowns')}</b><ul>${flow.limitations.map(s => `<li>${html(s)}</li>`).join('')}</ul><p>${t('이 그림은 실행 추적이나 DOM 커밋을 측정한 결과가 아닙니다. 조건·실패·병렬 경로는 시나리오와 기록된 한계로 확인하세요.', 'This diagram is not an executed trace or a DOM commit measurement. Check scenarios and limitations for conditional, failure and parallel paths.')}</p></div><details><summary>${t('같은 데이터의 Mermaid 중첩 블록', 'Mermaid nested blocks from the same data')}</summary><pre>${html(flowToMermaid(flow))}</pre></details></main>
<script type="application/json" id="flow-data">${data}</script><script>
const flow=JSON.parse(document.getElementById('flow-data').textContent);let scenario=flow.scenarios.find(s=>s.id===document.getElementById('scenario').value),step=0;
const ns='http://www.w3.org/2000/svg';const el=(name,attrs)=>{const e=document.createElementNS(ns,name);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e};
function draw(){const svg=document.getElementById('edges'),map=document.getElementById('map'),r=map.getBoundingClientRect();svg.replaceChildren();svg.setAttribute('width',r.width);svg.setAttribute('height',r.height);const defs=el('defs',{}),marker=el('marker',{id:'arrow',markerWidth:10,markerHeight:10,refX:8,refY:3,orient:'auto',markerUnits:'strokeWidth'});marker.append(el('path',{d:'M0,0 L0,6 L9,3 z',fill:'#bf5707'}));defs.append(marker);svg.append(defs);const edge=flow.edges.find(e=>e.id===scenario.steps[step].edge);const get=id=>[...map.querySelectorAll('[data-node]')].find(n=>n.dataset.node===id);const a=get(edge.from).getBoundingClientRect(),b=get(edge.to).getBoundingClientRect();const right=b.left>=a.right-5,left=b.right<=a.left+5;let x1=(left?a.left:a.right)-r.left,y1=a.top+a.height/2-r.top,x2=(right?b.left:b.right)-r.left,y2=b.top+b.height/2-r.top;const mid=right||left?(x1+x2)/2:Math.max(a.right,b.right)-r.left+16;let d=edge.from===edge.to?'M '+x1+' '+y1+' c -40,-40 -40,40 0,12':'M '+x1+' '+y1+' C '+mid+' '+y1+', '+mid+' '+y2+', '+x2+' '+y2;svg.append(el('path',{d,fill:'none',stroke:'#bf5707','stroke-width':2.5,'marker-end':'url(#arrow)'}));}
function showCitations(edge){const target=document.getElementById('edge-citations');target.replaceChildren();const relation=document.createElement('p');relation.textContent=edge.kind+' · '+edge.from+' → '+edge.to+(edge.condition?${JSON.stringify(t(' · 조건: ', ' · Condition: '))}+edge.condition:'');target.append(relation);for(const id of edge.evidence){const c=flow.evidence[id];if(!c)continue;const p=document.createElement('p'),b=document.createElement('b'),pre=document.createElement('pre');b.textContent=c.path+(c.line?':'+c.line:'');pre.textContent=c.quote;p.append(b,pre);target.append(p);}if(!edge.evidence.length){const p=document.createElement('p');p.textContent=${JSON.stringify(t('구현 근거 없음 · 설계 제안', 'No implementation evidence · proposed design'))};target.append(p);}}
function render(){const active=flow.edges.find(e=>e.id===scenario.steps[step].edge),affected=new Set([scenario.entry]);scenario.steps.forEach(s=>{const e=flow.edges.find(e=>e.id===s.edge);affected.add(e.from);affected.add(e.to)});for(const id of [...affected]){let n=flow.nodes.find(n=>n.id===id);while(n&&n.parent){affected.add(n.parent);n=flow.nodes.find(x=>x.id===n.parent)}}document.querySelectorAll('[data-node]').forEach(n=>{n.classList.toggle('affected',affected.has(n.dataset.node));n.classList.toggle('dim',!affected.has(n.dataset.node));n.classList.toggle('active',[active.from,active.to].includes(n.dataset.node))});document.getElementById('event').textContent=scenario.event;document.getElementById('outcome').textContent=scenario.outcome+(scenario.limitations.length?${JSON.stringify(t(' · 한계: ', ' · Limitations: '))}+scenario.limitations.join('; '):'');const list=document.getElementById('steps');list.replaceChildren();scenario.steps.forEach((s,i)=>{const e=flow.edges.find(e=>e.id===s.edge),li=document.createElement('li'),button=document.createElement('button');button.textContent=e.label;button.className=i===step?'selected':'';button.onclick=()=>{step=i;render()};li.append(button);list.append(li)});showCitations(active);document.getElementById('effect').textContent=(step+1)+'. '+scenario.steps[step].effect+(scenario.steps[step].condition?${JSON.stringify(t(' · 조건: ', ' · Condition: '))}+scenario.steps[step].condition:'');requestAnimationFrame(draw);}
document.getElementById('scenario').onchange=e=>{scenario=flow.scenarios.find(s=>s.id===e.target.value);step=0;render()};document.getElementById('next').onclick=()=>{step=(step+1)%scenario.steps.length;render()};document.getElementById('previous').onclick=()=>{step=(step+scenario.steps.length-1)%scenario.steps.length;render()};new ResizeObserver(draw).observe(document.getElementById('map'));document.querySelectorAll('details').forEach(e=>e.addEventListener('toggle',draw));render();
</script></html>`;
}
